### ISSUE TITLE
Fly.io health check

### ISSUE THREAD

**Issue by userbradley** [userbradley/documentation.breadnet.co.uk#222]
```toml
[[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/healthcheck"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false
    [services.http_checks.headers]
```
