### ISSUE TITLE
Helm iterate over key values

### ISSUE THREAD

**Issue by userbradley** [userbradley/documentation.breadnet.co.uk#288]
```yaml
config
  sshKeys:
    sftpgo-ssh-ecdsa-private: "id_ecdsa"
    sftpgo-ssh-ecdsa-public: "id_ecdsa.pub"
    sftpgo-ssh-ed25519-private: "id_ed25519"
    sftpgo-ssh-ed25519-public: "id_ed25519.pub"
    sftpgo-ssh-rsa-4096-private: "id_rsa"
    sftpgo-ssh-rsa-4096-public: "id_rsa.pub"
```

```go
    {{- range $k,$v := .Values.application.sshKeys}} {{/* Loops through the key value list of SSH keys */}}
    - secretKey: {{$v}}
      remoteRef:
        key: {{$k}}
    {{- end }}
```
