### ISSUE TITLE
CI to lint markdown

### ISSUE THREAD

**Issue by userbradley** [userbradley/documentation.breadnet.co.uk#448]
```yaml

name: check-markdown
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: tj-actions/changed-files@v45
      id: changed-files
      with:
        files: '**/*.md'
        separator: ","
        
    - uses: DavidAnson/markdownlint-cli2-action@v17
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        separator: ","
        config: ./.github/.markdownlint.json
```

https://github.com/swisskyrepo/InternalAllTheThings/actions/runs/12284137575/workflow
