### ISSUE TITLE
mdlint pre-commit

### ISSUE THREAD

**Issue by userbradley** [userbradley/documentation.breadnet.co.uk#458]
```yaml
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.1
    hooks:
      - id: markdownlint-cli2
        args: ["--config", "./.github/config/.markdownlint.json"]
```
