### ISSUE TITLE
Talos OIDC: Setup OIDC using passkeys

### ISSUE THREAD

**Issue by userbradley** [userbradley/documentation.breadnet.co.uk#526]
```
E0614 00:29:57.960378       1 authentication.go:75] "Unable to authenticate the request" err="[invalid bearer token, oidc: email not verified]"
```

Set the emails to verified in settings

```yaml
users:
 - name: pass-key
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://pass-keys.breadnet.co.uk
      - --oidc-client-id=<client ID>
      - --oidc-client-secret=<secret>
      - --oidc-extra-scope=groups
      - --oidc-extra-scope=email
      - --oidc-extra-scope=name
      command: kubectl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: true
```

```yaml
cluster:
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.33.1 # The container image used in the API server manifest.
        # Extra certificate subject alternative names for the API server's certificate.
        extraArgs:
            oidc-issuer-url: https://pass-keys.breadnet.co.uk
            oidc-client-id: <client ID>
            oidc-username-claim: sub
            oidc-groups-claim: groups
            oidc-groups-prefix: "oidc:"
```
